<?php

namespace Tests\Feature;

use App\Models\Media;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class SyncMediaFromStorageCommandTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function it_inserts_a_media_record_for_an_untracked_file(): void
    {
        $disk = Storage::fake(config('filesystems.default'));
        $disk->put('media/untracked.png', 'fake-bytes');

        $this->artisan('media:sync')->assertExitCode(0);

        $this->assertDatabaseHas('media', ['path' => 'media/untracked.png']);
    }

    #[Test]
    public function it_does_not_create_a_duplicate_record_for_a_backfilled_webp_sibling(): void
    {
        $disk = Storage::fake(config('filesystems.default'));
        $disk->put('media/example.png', 'fake-png-bytes');
        // A WebP sibling generated by media:backfill-webp — it must not get
        // its own Media row; only the original .png is tracked.
        $disk->put('media/example.webp', 'fake-webp-bytes');

        Media::factory()->create(['path' => 'media/example.png']);

        $this->artisan('media:sync')
            ->expectsOutputToContain('All storage files already have media records.')
            ->assertExitCode(0);

        $this->assertDatabaseMissing('media', ['path' => 'media/example.webp']);
        $this->assertDatabaseCount('media', 1);
    }

    #[Test]
    public function a_standalone_webp_upload_with_no_original_sibling_is_still_synced(): void
    {
        $disk = Storage::fake(config('filesystems.default'));
        $disk->put('media/standalone.webp', 'fake-webp-bytes');

        $this->artisan('media:sync')->assertExitCode(0);

        $this->assertDatabaseHas('media', ['path' => 'media/standalone.webp']);
    }
}
